### PR TITLE
Pull Request #1 (Player Render and update watermark)

### PR DESCRIPTION
**Pull request by deeoxys**
Going to make some pull requests one by one so that I don't break everything at once. Sorry for the confusion yesterday.

Changes:
+Added scaleable player render to HUD components.
+Changed SalHack.java name so that it says SalHackSkid.
+Changed SalHack.java version so that it has the SalHackSkid version number.

I beleive I fixed the crashing issue.

### CODE REVIEW

**Comment by deeoxys** [comment]
More changes:
+Add bed aura module. (Currently very basic;
Player places bed to set position. Then when active the module will explode the bed if holding another bed, then places a bed to replace the exploded one.)
+Change PvP HUD info component to include bed aura.

**Comment by deeoxys** [comment]
More changes 2:
+Add anchor surround module.
+Change pvp hud info component to include this module.

**Comment by deeoxys** [comment]
More changes 3:
+Change hud components so they are all unified with grey text for variable and white text for value.
+Changed speed component to allow BPS or km/h. // Perhaps change BPS to m/s?

**Comment by deeoxys** [comment]
More changes 4:
+Minor change in speed KMH, oversighted that speed was a float; it isnt. So extra bit isnt needed.

**Comment by deeoxys** [comment]
More changes 5:
+Change autototem and offhand chat notifier to blue instead of purple (so it doesnt look like a PM)

**Comment by liu7d7** [comment]
sure man!

**Pull request merged**
